### ISSUE TITLE
EvoSuite is able to cover some snippets with fewer tests than SnippetInputChecker

### ISSUE THREAD

**Issue by micskeiz** [SETTE-Testing/sette-snippets#7]
EvoSuite reaches 100% coverage with fewer inputs than SnippetInputchecker for B6a_CheckedExceptions_tryCatchFinally and B6b_CheckedExceptions_trycatchFinally.

EvoSuites's inputs:

```
1, 0, 0
(-2899), (-2), 0
(-2899), 3154, 3
(-2), 0, 3154
3154, 3154, 0
3154, (-1), (-2899)
0, 0, (-2899)
```

They do not have all possible return values (because the snippets uses a finally block that could overwrite the original return value), but cover all lines and branches.

Maybe just add a comment to B6a_CheckedExceptions_Inputs saying that these inputs are not minimal.

**Comment by LajosCseppento** [comment]
Fixed 42289d5
