### ISSUE TITLE
Required coverage of L2_addWithCondition

### ISSUE THREAD

**Issue by micskeiz** [SETTE-Testing/sette-snippets#8]
- Required coverage for the snippet: 83%
- SnippetInputChecker: 92,31% coverage with 6 inputs
- Some runs for EvoSuite: 84,62% coverage with 5 input

These are the tests generated by EvoSuite (run-01-30sec):

```
(String) null, (String) null
(String) null, ""
 "", (String) null
("", "ab")
\QuPH?gm,!6Uo<q?E+", "tcs<@u+>}~-o (O)Q"
```

These do not cover the following branch:

``` java
else if ((a + b).equals("ab") && a.equals("a")) {
    return 2;
```

Which is correctly detected by the evaluation in the coverage report.

Is the snippet's required coverage wrong?

**Comment by LajosCseppento** [comment]
Fixed 6ff0f2d
